version: '3.7'

networks:
  dev:
    driver: bridge

volumes:
  mysql_db_data:
    driver: local
  maria_db_data:
    driver: local
  pgsql_db_data:
    driver: local
  redis_db_data:
    driver: local
  redisinsight_data:
    driver: local

services:
  httpd:
    container_name: ${DOCKER_DOMAIN}-httpd
    image: ${DOCKER_DOMAIN}-php:7.2.15-apache
    build:
      context: .
      dockerfile: Dockerfile_Httpd
    volumes:
      - ./:/var/www/html/
    ports:
      - ${DOCKER_HTTPD_PORT}:80
    networks:
      - dev
    depends_on:
      - db_mysql
      - mailcatcher

  db_mysql:
    container_name: ${DOCKER_DOMAIN}-mysql
    image: mysql:5.7.26
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - dev
#    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: ${DOCKER_DOMAIN}-phpmyadmin
    image: phpmyadmin:5.2
    ports:
        - ${DOCKER_PHPMYADMIN_PORT}:80
    networks:
        - dev
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${DOCKER_DOMAIN}-${DB_CONNECTION}
        - PAM_PORT=${DOCKER_MYSQL_PORT}
        - PMA_USER=${DB_USERNAME}
        - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
        - db_mysql
